<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Huldra.Agent\Huldra.Agent.csproj" />
    <ProjectReference Include="..\Huldra.Shared\Huldra.Shared.csproj" />
  </ItemGroup>

</Project>
